export const names1960s = [
  "The Beatles",
  "James Brown",
  "The Beach Boys",
  "The Supremes",
  "The Rolling Stones",
  "Bob Dylan",
  "Aretha Franklin",
  "Elvis Presley",
  "Sam Cooke",
  "The Jimi Hendrix Experience",
  "Ray Charles",
  "Otis Redding",
  "The Temptations",
  "Smokey Robinson & The Miracles",
  "The Byrds",
  "Marvin Gaye",
  "The Four Seasons",
  "The Who",
  "Wilson Pickett",
  "Stevie Wonder",
  "The Kinks",
  "Roy Orbison",
  "The Impressions",
  "The Shirelles",
  "The Doors",
];

console.assert(names1960s.length === 25, "60s array must have 25 artists");

export const names1970s = [
  "David Bowie",
  "The Rolling Stones",
  "Stevie Wonder",
  "Bob Marley",
  "The Clash",
  "Led Zeppelin",
  "Neil Young",
  "Marvin Gaye",
  "Bruce Springsteen",
  "Pink Floyd",
  "Sex Pistols",
  "Elvis Costello",
  "Joni Mitchell",
  "John Lennon",
  "Ramones",
  "Bob Dylan",
  "Roxy Music",
  "Fleetwood Mac",
  "Queen",
  "The Who",
  "Lou Reed",
  "Van Morrison",
  "Kraftwerk",
  "Elton John",
  "Black Sabbath",
];

console.assert(names1970s.length === 25, "70s array must have 25 artists");

export const names1980s = [
  "Michael Jackson",
  "Prince",
  "Madonna",
  "U2",
  "Bruce Springsteen",
  "Kate Bush",
  "Van Halen",
  "Public Enemy",
  "Billy Joel",
  "The Police",
  "Phil Collins",
  "Guns N’ Roses",
  "Def Leppard",
  "Janet Jackson",
  "Wham!",
  "Whitney Houston",
  "Metallica",
  "Dire Straits",
  "AC/DC",
  "Lionel Richie",
  "Bon Jovi",
  "Talking Heads",
  "Genesis",
  "R.E.M.",
  "Duran Duran",
];

console.assert(names1980s.length === 25, "80s array must have 25 artists");

export const names1990s = [
  "Nirvana",
  "Pearl Jam",
  "Radiohead",
  "Blur",
  "Oasis",
  "2Pac",
  "Red Hot Chili Peppers",
  "Björk",
  "The Smashing Pumpkins",
  "Beastie Boys",
  "R.E.M.",
  "Dr. Dre",
  "Mariah Carey",
  "Alice In Chains",
  "Green Day",
  "Soundgarden",
  "Nine Inch Nails",
  "Rage Against The Machine",
  "U2",
  "Metallica",
  "A Tribe Called Quest",
  "Tool",
  "The Notorious B.I.G.",
  "PJ Harvey",
  "Faith No More",
];

console.assert(names1990s.length === 25, "90s array must have 25 artists");

export const names2000s = [
  "Outkast",
  "Eminem",
  "Coldplay",
  "Radiohead",
  "Kanye West",
  "Alicia Keys",
  "Linkin Park",
  "The White Stripes",
  "Green Day",
  "Red Hot Chili Peppers",
  "Jay Z",
  "Gorillaz",
  "Usher",
  "The Strokes",
  "Queens of the Stone Age",
  "Foo Fighters",
  "Missy Elliot",
  "Audioslave",
  "Beyoncé",
  "Franz Ferdinand",
  "Pearl Jam",
  "Muse",
  "System of a Down",
  "The Roots",
  "Destiny’s Child",
];

console.assert(names2000s.length === 25, "2000s array must have 25 artists");

export const names2010s = [
  "Kendrick Lamar",
  "Taylor Swift",
  "Bruno Mars",
  "Rihanna",
  "Adele",
  "Ed Sheeran",
  "Justin Bieber",
  "Katy Perry",
  "Post Malone",
  "The Chainsmokers",
  "Maroon 5",
  "Ariana Grande",
  "Imagine Dragons",
  "The Weeknd",
  "Nicki Minaj",
  "Eminem",
  "P!nk",
  "One Direction",
  "Justin Timberlake",
  "Drake",
  "Beyonce",
  "Sam Smith",
  "Kesha",
  "Lil Wayne",
  "Cardi B",
];

console.assert(names2010s.length === 25, "2010s array must have 25 artists");

export const names2020s = [
  "Post Malone",
  "The Weeknd",
  "Roddy Ricch",
  "DaBaby",
  "Drake",
  "Juice WRLD",
  "Lil Baby",
  "Harry Styles",
  "Taylor Swift",
  "Pop Smoke",
  "Billie Eilish",
  "Dua Lipa",
  "Luke Combs",
  "Lil Uzi Vert",
  "Justin Bieber",
  "Lewis Capaldi",
  "Sabrina Carpenter",
  "BTS",
  "Bad Bunny",
  "Chapell Roan",
  "Rod Wave",
  "Doja Cat",
  "Travis Scott",
  "Quavo",
  "Lizzo",
];

console.assert(names2020s.length === 25, "2020s array must have 25 artists");